// Generated by https://quicktype.io

export interface CheckoutResponse {
  transactionUuid: string;
  total: number;
  createdDate: string;
  transactionState: string;
  number: string;
  account: Account;
  shippingCost: number;
  pay: Pay;
  amountTaxes: number;
  amountTotal: number;
  description: string;
  quantity: number;
  transaction_type: string;
  orderDetailsList: OrderDetailsList[];
  shippingDetails: ShippingDetails;
}

export interface Account {
  accountUuid: string;
  email: string;
  password: string;
  rol: string;
  createdDate: string;
  lastSessionDate: string;
  active: boolean;
  verificationCode: string;
  tokenPassword: string;
  token: string;
}

export interface OrderDetailsList {
  orderDetailUuid: string;
  product: Product;
  quantity: number;
  price: number;
  totalAmount: number;
  taxesAmount: number;
  total: number;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  stock: number;
  image: string;
  price: number;
  weight: number;
  country: string;
  minStock: number;
  state: string;
  category: Category;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  number: string;
  state: boolean;
}

export interface Pay {
  transactionUuid: string;
  total: number;
  createdDate: string;
  transactionState: string;
  number: string;
  cardNumber: string;
  expirationDate: string;
  cardCode: string;
  description: string;
  orders: string;
  quantity: number;
  amountTaxes: number;
  amountTotal: number;
  paymentMethod: string;
  transaction_type: string;
  currencyCode: string;
  auth_code: string;
}

export interface ShippingDetails {
  shippingDetailUuid: string;
  name: string;
  lastName: string;
  company: string;
  address1: string;
  address2: string;
  postalCode: string;
  provincia: string;
  city: string;
  country: string;
  gift: boolean;
  order: string;
}

// Generated by https://quicktype.io

export interface FormCheckout {
  account: Account;
  shippingCost: number;
  orderDetailsList: OrderDetailsList[];
  shippingDetails: ShippingDetails;
}

export interface Account {
  accountUuid: string;
}

export interface OrderDetailsList {
  product: Product;
  quantity: number;
}

export interface Product {
  id: string;
}

export interface ShippingDetails {
  shippingdetail_uuid: string;
  name: string;
  lastName: string;
  address1: string;
  address2: string;
  postalCode: string;
  provincia: string;
  city: string;
  country: string;
  gift: boolean;
}
